/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practice;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author IT
 */
public class AddPassword extends javax.swing.JFrame {

    /**
     * Creates new form AddPassword
     */
    private User user;
    private ImageIcon icon;
    private JScrollPane jScrollPane1;

    public AddPassword(User user) {
        setResizable(false);
        this.user = user;
        setIcon();
        setLocations();
        setTitle("Add password");
        initComponents();
        jScrollPane1 = null;
    }

    public AddPassword(User user, JScrollPane sp) {
        setResizable(false);
        this.user = user;
        setIcon();
        setLocations();
        setTitle("Add password");
        initComponents();
        this.jScrollPane1 = sp;

    }

    public AddPassword() {
        setIcon();
        setLocations();
        setTitle("Add password");
        initComponents();
    }

    public void setIcon() {
        icon = new ImageIcon(getClass().getResource("/practiceIcons/addPassword.png"));
        this.setIconImage(icon.getImage());
    }

    public void setLocations() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - 379) / 2;
        int y = (screenSize.height - 240) / 2;
        setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        websiteName = new javax.swing.JTextField();
        addPass = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        userName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        websiteName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        websiteName.setForeground(new java.awt.Color(153, 153, 153));
        websiteName.setText("Website name");
        websiteName.setToolTipText("");
        websiteName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        websiteName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        websiteName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                websiteNameMouseClicked(evt);
            }
        });

        addPass.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        addPass.setText("Add");
        addPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPassActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("123456789");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });

        userName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(153, 153, 153));
        userName.setText("User name/User ID");
        userName.setToolTipText("");
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName)
                            .addComponent(websiteName, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(password)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(addPass)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(websiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void refreshPanel() {
        JPanel panel = (JPanel) jScrollPane1.getViewport().getView(); // Get the current panel in JScrollPane
        panel.removeAll(); // Remove all existing components

        // Add updated components
        ArrayList<PasswordAndWeb> list = user.getList();
        int y = 10;
        for (PasswordAndWeb data : list) {
            JLabel website = new JLabel(data.getWeb());
            website.setBounds(15, y, 180, 25);
            website.setOpaque(false);
            website.setBackground(new Color(0, 0, 0, 0));
            website.setFont(new java.awt.Font("Segoe UI", 1, 12));
            website.setForeground(new java.awt.Color(153, 153, 153));
            panel.add(website);

            JLabel handel = new JLabel(data.getHandel());
            handel.setOpaque(false);
            handel.setBounds(200, y, 150, 25);
            handel.setBackground(new Color(0, 0, 0, 0));
            handel.setFont(new java.awt.Font("Segoe UI", 1, 12));
            handel.setForeground(new java.awt.Color(153, 153, 153));
            panel.add(handel);

            JLabel pass = new JLabel(data.getPass());
            pass.setOpaque(false);
            pass.setBounds(390, y, 150, 25);
            pass.setBackground(new Color(0, 0, 0, 0));
            pass.setFont(new java.awt.Font("Segoe UI", 1, 12));
            pass.setForeground(new java.awt.Color(153, 153, 153));
            panel.add(pass);

            JButton actionButton = new JButton("Decrypt");
            actionButton.setBounds(550, y, 75, 25);
            actionButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
            actionButton.setForeground(new java.awt.Color(0, 102, 204));
            actionButton.setFocusPainted(false);
           actionButton.addActionListener(e -> {
                
                if (actionButton.getText().equals("Decrypt")) {
                    actionButton.setText("Encrypt");
                    String s=null;
                    try {
                        s=user.en.decrypt(data.getPass());
                        pass.setText(s);
                    } catch (Exception ex) {
                        Logger.getLogger(AllPassword.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    actionButton.setText("Decrypt");
                    String s=null;
                    try {
                        s=user.en.encrypt(data.getPass());
                        pass.setText(s);
                    } catch (Exception ex) {
                        Logger.getLogger(AllPassword.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    

                }
                // Add the desired functionality here
            });
            panel.add(actionButton);

            y += 30;
        }

        // Update the panel size
        panel.setPreferredSize(new Dimension(660, y));

        // Refresh and repaint
        panel.revalidate(); // Recalculates layout
        panel.repaint();    // Repaints the panel
    }

    private void websiteNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_websiteNameMouseClicked
        JLabel website = new JLabel("Website name");
        website.setBounds(35, 14, 180, 25);
        website.setOpaque(false);
        website.setBackground(new Color(0, 0, 0, 0));
        website.setFont(new java.awt.Font("Segoe UI", 1, 18));
        website.setForeground(new java.awt.Color(153, 153, 153));
        if (websiteName.getText().equals("Website name")) {
            websiteName.setText("");
            jPanel1.repaint();
        }
        jPanel1.add(website);

    }//GEN-LAST:event_websiteNameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        JLabel pass = new JLabel("Password");
        pass.setBounds(35, 88, 180, 25);
        pass.setOpaque(false);
        pass.setBackground(new Color(0, 0, 0, 0));
        pass.setFont(new java.awt.Font("Segoe UI", 1, 18));
        pass.setForeground(new java.awt.Color(153, 153, 153));
        if (password.getText().equals("123456789")) {
            jPanel1.repaint();
            password.setText("");
        }
        jPanel1.add(pass);
    }//GEN-LAST:event_passwordMouseClicked

    private void addPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPassActionPerformed
        String pass=null;
        try {
            pass=user.en.encrypt(password.getText());
        } catch (Exception ex) {
            Logger.getLogger(AddPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        PasswordAndWeb data = new PasswordAndWeb(pass, websiteName.getText(), userName.getText());
        user.addPassToList(data);
        DatabaseConnection db = new DatabaseConnection(user);
        db.addPasswordToDb();
        if (jScrollPane1 != null) {
            refreshPanel();
        }

        this.dispose();
    }//GEN-LAST:event_addPassActionPerformed

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        // TODO add your handling code here:
        JLabel userNames = new JLabel("User name/User ID");
        userNames.setBounds(35, 164, 180, 25);
        userNames.setOpaque(false);
        userNames.setBackground(new Color(0, 0, 0, 0));
        userNames.setFont(new java.awt.Font("Segoe UI", 1, 18));
        userNames.setForeground(new java.awt.Color(153, 153, 153));
        if (userName.getText().equals("User name/User ID")) {
            userName.setText("");
            jPanel1.repaint();
        }
        jPanel1.add(userNames);
    }//GEN-LAST:event_userNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField websiteName;
    // End of variables declaration//GEN-END:variables
}
