
package practice;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class AllPassword extends javax.swing.JFrame {

    /**
     * Creates new form AllPassword
     */
    private User user;
    private ImageIcon icon;
    public AllPassword(User user) {
        setResizable(false);
        this.user=user;
        setIcon();
        setLocationRelativeTo(null);
        setLocations();
        initComponents();
        setTitle("All passwords");
        initData();
        setSize(675, 500);
    }
    public void setLocations()
    {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - 675)/2 ;
        int y = (screenSize.height - 500)/2;
        setLocation(x, y);
        
    }
    public void setIcon(){
        icon=new ImageIcon(getClass().getResource("/practiceIcons/mainIcon.png"));
        this.setIconImage(icon.getImage());
    }
    public void initData()
    {
        
        String[] column={"Website name","Passwords"};
        DefaultTableModel tableModel=new DefaultTableModel(column,0);
        JTable table=new JTable(tableModel);
        for(PasswordAndWeb data:user.getList()){
            String website,password;
            website=data.getWeb();
            password=data.getPass();
            tableModel.addRow(new Object[]{website,password});
        }
        JScrollPane sp=new JScrollPane(table);
        getContentPane().setLayout(new java.awt.BorderLayout()); // Set layout to BorderLayout
    getContentPane().add(sp, java.awt.BorderLayout.CENTER); // Add scroll pane to center
    
    // Call pack to fit the components in the frame
    pack();
         this.revalidate();
    this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ProfileMenu = new javax.swing.JMenu();
        profileMenuBtn = new javax.swing.JMenuItem();
        addPassMenu = new javax.swing.JMenuItem();
        seeAllPassMenu = new javax.swing.JMenuItem();
        logOutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ProfileMenu.setBackground(new java.awt.Color(153, 255, 204));
        ProfileMenu.setForeground(new java.awt.Color(0, 102, 102));
        ProfileMenu.setText("||||");
        ProfileMenu.setToolTipText("");
        ProfileMenu.setBorderPainted(false);
        ProfileMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileMenu.setFocusPainted(true);

        profileMenuBtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        profileMenuBtn.setText("Profile");
        profileMenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuBtnActionPerformed(evt);
            }
        });
        ProfileMenu.add(profileMenuBtn);

        addPassMenu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        addPassMenu.setText("Add new Password");
        addPassMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPassMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPassMenuActionPerformed(evt);
            }
        });
        ProfileMenu.add(addPassMenu);

        seeAllPassMenu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        seeAllPassMenu.setText("See all passwords");
        seeAllPassMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileMenu.add(seeAllPassMenu);

        logOutMenu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        logOutMenu.setText("Log out");
        logOutMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuActionPerformed(evt);
            }
        });
        ProfileMenu.add(logOutMenu);

        jMenuBar1.add(ProfileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuBtnActionPerformed
         this.dispose();
         UserWindow window=new UserWindow(user);
         window.setVisible(true);
    }//GEN-LAST:event_profileMenuBtnActionPerformed

    private void addPassMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPassMenuActionPerformed
         AddPassword addWindow=new AddPassword(user);
         addWindow.setVisible(true);
         initData();
    }//GEN-LAST:event_addPassMenuActionPerformed

    private void logOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuActionPerformed
        this.dispose();
        LogInWindow log = new LogInWindow();
        log.setVisible(true);
    }//GEN-LAST:event_logOutMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllPassword(new User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ProfileMenu;
    private javax.swing.JMenuItem addPassMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logOutMenu;
    private javax.swing.JMenuItem profileMenuBtn;
    private javax.swing.JMenuItem seeAllPassMenu;
    // End of variables declaration//GEN-END:variables
}
